### ISSUE TITLE
dashboard backend error

### ISSUE THREAD

**Issue by y-ka-adglobe-co-jp** [KLab/wsnet2#82]
We got an error when calling make re-run in container

```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
mkdir -p ./src/pb
npx grpc_tools_node_protoc \
  --plugin=protoc-gen-ts="node_modules/.bin/protoc-gen-ts" \
  --js_out="import_style=commonjs,binary:./src/pb" \
  --grpc_out="grpc_js:./src/pb" \
  --ts_out="service=grpc-node,mode=grpc-js:./src/pb" \
  -I ../../server/pb ../../server/pb/app.proto ../../server/pb/clientinfo.proto ../../server/pb/gameservice.proto ../../server/pb/roominfo.proto ../../server/pb/roomoption.proto ../../server/pb/timestamp.proto
cd go-binary && gopherjs build -o ../src/plugins/binary.js
../../../server/pb/timestamp.go:12:11: undeclared name: Timestamp
../../../server/pb/timestamp.go:21:11: undeclared name: Timestamp
../../../server/pb/timestamp.go:25:11: undeclared name: Timestamp
../../../server/pb/timestamp.go:29:11: undeclared name: Timestamp
../../../server/pb/timestamp.go:33:11: undeclared name: Timestamp
../../../server/pb/timestamp.go:44:33: undeclared name: Timestamp
../../../server/pb/timestamp.go:45:33: undeclared name: Timestamp
../../../server/pb/roominfo.go:14:10: undeclared name: RoomInfo
../../../server/pb/roominfo.go:21:10: undeclared name: RoomNumber
../../../server/pb/roominfo.go:40:10: undeclared name: RoomNumber
../../../server/pb/roominfo.go:40:10: too many errors
make: *** [Makefile:39: src/plugins/binary.js] Error 1

Can you help us to resolve this error?

**Comment by makiuchi-d** [comment]
It is needed to run `make generate` in the `server` directory.
Ideally, this should be called in the `wsnet2-dashboard/backend/Makefile`.
However, this job requires go 1.22, which might not be installed to the container.
We will be updating the Makefile and Dockerfile for the dashboard-backend going forward.
